version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./src:/app
    environment:
    - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"